# Generated by Django 2.0.9 on 2018-12-11 16:42

from django.db import migrations, models
import django.db.models.deletion
import tenant_schemas.postgresql_backend.base
import tenants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            managers=[
                ('objects', tenants.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TenantMaster',
            fields=[
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_description', models.TextField(default='')),
                ('company_address', models.CharField(default='', max_length=200)),
                ('company_city', models.CharField(default='', max_length=200)),
                ('contry_code', models.CharField(default='', max_length=200)),
                ('company_phone', models.CharField(default='', max_length=200)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_contact', models.CharField(default='', max_length=200)),
                ('company_active', models.BooleanField(default=False)),
                ('control', models.CharField(default='', max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.TenantMaster'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('tenant', 'email')},
        ),
    ]
