# Generated by Django 2.1.4 on 2018-12-14 14:45

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.TextField(default='')),
                ('company_address', models.CharField(blank=True, max_length=200, null=True)),
                ('company_city', models.CharField(blank=True, max_length=200, null=True)),
                ('contry_code', models.CharField(blank=True, max_length=200, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_contact', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('company_active', models.BooleanField(default=False)),
                ('control', models.CharField(default='', max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenants',
                'verbose_name_plural': 'Tenants',
            },
        ),
    ]
